baseURL = 'http://hogus.work/'
theme = "hogusource-tailwind"
languageCode = "ja"
title = "QUICK INSTANT"
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]

taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]
[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    lineNos = false
    guessSyntax = false
    hl_Lines = ""
    tabWidth = 4
    # ⬇ コレ！
    noCopyButton = true
[markup.goldmark.renderer]
unsafe = true
[params]
googleAnalytics = "G-GJNS8STNX9"